{ config, lib, pkgs, ... }:

let
  hosts = config.services.sshConfigHost;
in
{
  options.services.sshConfigHost = lib.mkOption {
    type = lib.types.attrsOf (lib.types.submodule ({_name, ...}: {
      options = {
        enabled = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = "Whether this item is enabled";
        };

        host = lib.mkOption {
          type = lib.types.str;
          default = _name;
          description = "Host to create an `ssh_config` listing for";
        };

        hostname = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          description = "Hostname to use for host";
          default = null;
        };

        identityFile = lib.mkOption {
          type = lib.types.nullOr lib.types.path;
          description = "Identity file to use for host";
          default = null;
        };

        user = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          description = "Username to use if one is not supplied in the command";
          default = null;
        };
      };
    }));
    default = {};
    description = "Hosts to make `ssh_config` listings for";
  };
  
  config = lib.mkIf (hosts != {}) {
    environment.etc = lib.mapAttrs' (hostname: host_options:
      lib.nameValuePair ( "ssh/ssh_config.d/${hostname}-identity.conf" ) {
        text = ''
          # Generated by gitSshConfig module
          Host ${hostname}
              User git
              IdentityFile "${host_options.identityFile}"
        '';
        mode = "0644";  # Readable by all users
      }
    ) hosts;

    programs.ssh.extraConfig = lib.strings.concatStringsSep "\n" ( lib.mapAttrsToList (hostname: host_options: 
      "Include /etc/ssh/ssh_config.d/${hostname}-identity.conf"
    ) hosts );
  };
}
